image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

environment:
  matrix:
    - PLATFORM: x86
      QTDIR: C:\Qt\5.14\msvc2017
      GENERATOR: Visual Studio 16 2019
      ARCHITECTURE: Win32
    - PLATFORM: x64
      QTDIR: C:\Qt\5.14\msvc2017_64
      GENERATOR: Visual Studio 16 2019
      ARCHITECTURE: x64

install:
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - cmake -G"%GENERATOR%" -A %ARCHITECTURE% -DCMAKE_PREFIX_PATH=%QTDIR% -DCMAKE_INSTALL_PREFIX=./install .

build_script:
  - cmake --build . --config %CONFIGURATION%

after_build:
  - cmake --build . --config %CONFIGURATION% --target PACKAGE

on_failure:
  - pwsh: |
      Write-Output '# Environment variables:'
      Get-ChildItem env:

      Write-Output '# WiX log file:'
      $packagePlatformDesignator = if ($env:PLATFORM -eq 'x86') { 'win32' } else { 'win64' }
      $wixLogFilePath = "./_CPack_Packages/$packagePlatformDesignator/WIX/wix.log"
      Write-Output "($wixLogFilePath)"
      if (Test-Path $wixLogFilePath) {
        Get-Content $wixLogFilePath
      } else {
        Write-Output "not found"
      }

test_script:
  - ctest --output-on-failure

artifacts:
  - path: '*.msi'
    name: Installer

deploy:
  provider: GitHub
  auth_token:
    secure: MVgt4cKpKisTbEIcPEnaLBfUpYGxzN0CBf3ReEOFbVOp35O9WUuMCF2lzI4IsGqk
  artifact: Installer
  on:
    appveyor_repo_tag: true
    configuration: Release
