sudo: required
dist: xenial
language: minimal
services:
- docker
os:
- linux
matrix:
  include:
    os: osx
    language: cpp
    osx_image: xcode9.4
    services: {}
    cache:
      directories:
        - /usr/local/Homebrew
        - $HOME/Library/Caches/Homebrew
    before_install:
    - brew update
    - brew install qt
    - brew link --force qt
    install:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix qt)
    - make package VERBOSE=1 DESTDIR=$(pwd)/install
    script:
    - make test
    before_deploy:
    - export RELEASE_DMG_FILE=$(ls Fips-*.dmg)
    - echo "deploying $RELEASE_DMG_FILE"
    deploy:
      - provider: releases
        api_key:
          secure: I4SgyRVqHPF8f+QhyfiAXlsd98/NesRliYBap5cq1pt3/XyTREwfoYnA0rwNZ6r5oovEkQuy11tIL5k5WZuCOxqEKNqQYhLpi3Io42NX+49vS2jMTDyarE00c6YA4bLesPJQuXWWX7zdNlR6n/6MQLTL4BX5OtYfWP2xGnbzNZfkkaKUphU1rzuzPjK+y6EsglYCwSJuZMQduc+TzESQUyZ32S4mv97w3m8UTRSocIYCcNdxyuBCXMiebyprLcd2UwwrADthJTMIzRJ8298xEMfQRIoACxJou2QDhfjnLtqD1ojd+9PjPzER1zkVrwYESLiEiZLEvRCqUcbuz0iCo6LAOOrQhEOGv1yr6wXDcFeQtWjprBelTbkWyDCPktdkLRszhvrO+Q/abs+bTm+TnOt52Ax/SVC1hSF7pWfbBdzaHYeo80BaphkiF3K5bysogb1nSQjfppEY+zLfYdHl69S6RMxiF6j9RRLi8biCzUNROl/xDHvM+y5HmGoJLk04ciTIiMr7zSM4rd4m7ia3VB2i21fFA2unMgpBy5vrfTsoeonn1HSzT/TMOKFfnVClOibekAoGm66jWLqVHGVBv0D0s2MLVVJBzq855iIeFk86VTwDXJY+BZKMHqbiQ8aqoZL/97D/h4pOSFeQo975PSFoEMrMHqCpLNtc81Wci/k=
        file: "${RELEASE_DMG_FILE}"
        skip_cleanup: true
        on:
          tags: true
          branch: master
      - provider: script
        script: curl --upload-file ${RELEASE_DMG_FILE} https://transfer.sh/${RELEASE_DMG_FILE} || true
        skip_cleanup: true
        on:
          all_branches: true

env:
- BASE_IMAGE_TAG=gcc9-qt513
- BASE_IMAGE_TAG=gcc9-qt512
- BASE_IMAGE_TAG=gcc9-qt59
- BASE_IMAGE_TAG=gcc8-qt513
- BASE_IMAGE_TAG=gcc8-qt512
- BASE_IMAGE_TAG=gcc8-qt59
- BASE_IMAGE_TAG=gcc7-qt513
- BASE_IMAGE_TAG=gcc7-qt512
- BASE_IMAGE_TAG=gcc7-qt59
- BASE_IMAGE_TAG=gcc4.8-qt56
- BASE_IMAGE_TAG=clang9-qt513
- BASE_IMAGE_TAG=clang9-qt512
- BASE_IMAGE_TAG=clang9-qt59
- BASE_IMAGE_TAG=clang8-qt513
- BASE_IMAGE_TAG=clang8-qt512
- BASE_IMAGE_TAG=clang8-qt59
- BASE_IMAGE_TAG=clang7-qt513
- BASE_IMAGE_TAG=clang7-qt512
- BASE_IMAGE_TAG=clang7-qt59
install:
- cat Dockerfile.in | m4 -DBASE_IMAGE_TAG=${BASE_IMAGE_TAG} > Dockerfile
- docker build . -t test
script:
- docker run --security-opt seccomp=unconfined test
